name: Build image and publish

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: build and push image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Connect Tailscale
      uses: tailscale/github-action@v2
      with:
        # Your Tailscale authentication key, from the admin panel.
        authkey: ${{ secrets.TS_AUTHKEY }}
        hostname: temp-runner

    - name: Docker Login
      uses: docker/login-action@v3.6.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: bucciarati.tail5b1a8.ts.net
        # Username used to log against the Docker registry
        username: moody
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.REGISTRY_PASSWORD }}
        # Specifies whether the given registry is ECR (auto, true or false)
        # ecr: # optional
        # Log out from the Docker registry at the end of a job
        # logout: # optional, default is true
        # Raw authentication to registries, defined as YAML objects
        # registry-auth: # optional

    - name: Build the Docker image
      run: | 
        docker build . --file Dockerfile \
        --tag bucciarati.tail5b1a8.ts.net/ts-exporter:$(git rev-parse --short HEAD) \
        --tag bucciarati.tail5b1a8.ts.net/ts-exporter:main \
        --tag ts-exporter:$(git rev-parse --short HEAD)

    - name: Push image to registry
      run: |
        ls
        docker image push bucciarati.tail5b1a8.ts.net/ts-exporter:$(git rev-parse --short HEAD)
        docker image push bucciarati.tail5b1a8.ts.net/ts-exporter:main


    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.FF_SSH_KEY }}
    
    - name: SSH into server
      run: |
        ssh -o StrictHostKeyChecking=no moody@foofighters "cd ~/le_docks/ts-exporter; docker compose pull; docker compose up -d"

